from __future__ import annotations

from dataclasses import dataclass, field
from uuid import uuid4

from erpguard.recording_pipeline.ui_recording_session import UIRecordingSessionService
from erpguard.recording_pipeline.ui_event_capture import UIEventCaptureService
from erpguard.recording_pipeline.ui_recording_normalizer import UIRecordingNormalizerService
from erpguard.recording_pipeline.ui_skill_draft_builder import UISkillDraftBuilder
from erpguard.recording_pipeline.ui_skill_compiler import UISkillCompilerService
from erpguard.product.skill_versioning import UISkillVersioningService
from erpguard.product.skill_lifecycle import UISkillLifecycleService
from erpguard.product.active_skill_runner import ActiveSkillRunnerService
from erpguard.product.skill_schedule import SkillScheduleService

_DEMO_TARGET = "http://127.0.0.1:8000/fake-erp"


@dataclass(frozen=True)
class DemoSeedResult:
    session_id: str
    draft_id: str
    skill_id: str
    compiled_skill_id: str
    version_id: str
    run_id: str
    schedule_id: str
    scenario_label: str
    erp_target: str
    safety_invariants: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)


class OperatorDemoSeedService:
    _sessions = UIRecordingSessionService()
    _events = UIEventCaptureService()
    _normalizer = UIRecordingNormalizerService()
    _draft_builder = UISkillDraftBuilder()
    _compiler = UISkillCompilerService()
    _versioning = UISkillVersioningService()
    _lifecycle = UISkillLifecycleService()
    _runner = ActiveSkillRunnerService()
    _schedules = SkillScheduleService()

    def seed(self, operator: str = "demo_operator") -> DemoSeedResult:
        # 1. Create recording session
        session = self._sessions.create_session(
            name="Demo — Fake ERP Formula Review",
            description="Operator demo seed: controlled recording on Fake ERP only.",
            target_base_url=_DEMO_TARGET,
        )
        sid = session.session_id

        # 2. Inject synthetic events
        self._events.capture_event(sid, "navigate", url=_DEMO_TARGET + "/sales/orders")
        self._events.capture_event(sid, "fill", selector="[data-testid='order-search']", input_value="SO-VALID")
        self._events.capture_event(sid, "click", selector="[data-testid='open-order-SO-VALID']")
        self._events.capture_event(sid, "click", selector="[data-testid='formula-tab']")

        # 3. Finish session
        self._sessions.finish_session(sid)

        # 4. Normalize + build draft
        raw = self._events.list_events(sid)
        recording = self._normalizer.normalize(sid, raw)
        draft = self._draft_builder.build_draft(
            recording,
            name="Demo Skill — Fake ERP Formula Review",
            description="Auto-generated by operator demo seed. Fake ERP only.",
        )

        # 5. Compile
        compiled = self._compiler.compile(draft.draft_id)

        # 6. Create version → promote → approve → activate
        skill_family = f"demo_family_{uuid4().hex[:12]}"
        version = self._versioning.create_from_compiled_skill(
            compiled.compiled_skill_id,
            skill_id=skill_family,
        )
        version_id = version.version_id
        self._lifecycle.promote_to_candidate(version_id, actor=operator)
        self._lifecycle.approve(version_id, actor=operator)
        self._lifecycle.activate(version_id, actor=operator)

        # 7. Manual run (against Fake ERP)
        run = self._runner.run(
            version_id=version_id,
            target_base_url=_DEMO_TARGET,
            actor=operator,
            inputs={},
        )

        # 8. Create 60s schedule → activate
        schedule = self._schedules.create_schedule(
            version_id=version_id,
            name="Demo 60s Schedule",
            interval_seconds=60,
            target_base_url=_DEMO_TARGET,
            min_interval_seconds=60,
            dedup_window_seconds=5,
            inputs={},
            created_by=operator,
        )
        self._schedules.activate(schedule.schedule_id, actor=operator, reason="demo seed activation")

        return DemoSeedResult(
            session_id=sid,
            draft_id=draft.draft_id,
            skill_id=skill_family,
            compiled_skill_id=compiled.compiled_skill_id,
            version_id=version_id,
            run_id=run.run_id,
            schedule_id=schedule.schedule_id,
            scenario_label="Fake ERP Formula Review — End-to-End Demo",
            erp_target=_DEMO_TARGET,
            safety_invariants=[
                "erp_target=fake_only",
                "no_llm_replay",
                "no_real_odoo_browser_automation",
                "no_coordinate_fallback",
                "no_automatic_repair",
                "no_background_scheduler",
                "no_mcp_execution_gateway",
                "no_new_erp_write_categories",
                "no_r3_r4_operations",
            ],
            notes=[
                f"Recording session: {sid}",
                f"Compiled skill: {compiled.compiled_skill_id}",
                f"Active version: {version_id}",
                f"Manual run: {run.run_id} status={run.status}",
                f"Schedule: {schedule.schedule_id} interval=60s",
            ],
        )
